---
# https://pre-commit.com/#installation
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #  rev: v1.1.10
  #  hooks:
  #    - id: remove-tabs
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        name: Run codespell
        description: Check spelling with codespell
        entry: codespell --ignore-words=codespell.txt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        name: Run markdownlint
        entry: markdownlint -c .github/linters/.markdown-lint.yml .
        exclude: ^\.github/.*$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint --strict -c .github/linters/.yaml-lint.yml .
        types: [yaml]
